/**
 * Generates src/data/keywordIndex.ts: a lightweight slug + keyword list for
 * every keyword page. KeywordPage.tsx uses this (a few KB) to build related
 * links instead of importing the full ~1MB keywordPages dataset into its chunk.
 *
 * Runs before `vite build` so the index is always in sync with the page data.
 *   npx tsx scripts/gen-keyword-index.ts
 */

import { writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { keywordPages } from "../src/data/keywordPages";
import { generatedBlogPosts } from "../src/data/blogPosts";
import { generatedBlogPosts2 } from "../src/data/blogPosts2";
import { longFormArticles } from "../src/data/longform";
import { imageForPage } from "../src/lib/pageImages";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const index = Object.values(keywordPages).map((p) => ({ slug: p.slug, keyword: p.keyword }));

const out = `// AUTO-GENERATED by scripts/gen-keyword-index.ts — do not edit by hand.
// Lightweight slug + keyword index used by KeywordPage for related-links
// scoring without pulling the full keywordPages dataset into the page chunk.
export interface KeywordIndexEntry {
  slug: string;
  keyword: string;
}

export const keywordIndex: KeywordIndexEntry[] = ${JSON.stringify(index)};
`;

const target = join(__dirname, "..", "src", "data", "keywordIndex.ts");
writeFileSync(target, out, "utf-8");
console.log(`✓ Generated keywordIndex.ts with ${index.length} entries`);

const slugs = index.map((p) => p.slug);
const fnOut = `// AUTO-GENERATED — do not edit.
export const KEYWORD_SLUGS = new Set<string>(${JSON.stringify(slugs)});
`;
writeFileSync(join(__dirname, "..", "functions/_lib/keywordSlugs.ts"), fnOut, "utf-8");
console.log(`✓ Generated functions/_lib/keywordSlugs.ts with ${slugs.length} slugs`);

const KEEPERS: { slug: string; category: string; title: string; excerpt: string; date: string }[] = [
  { slug: "future-of-search-generative-ai-dubai", category: "SEO Strategy", title: "The Future of Search: Preparing for Generative AI in Dubai", excerpt: "How generative engine optimisation (GEO) is reshaping search visibility for businesses across Dubai and the UAE.", date: "Nov 10, 2025" },
  { slug: "core-web-vitals-matter", category: "Technical SEO", title: "Why Core Web Vitals Matter More Than Ever", excerpt: "A deep dive into site speed, interactivity, and visual stability as crucial Google ranking factors for your website.", date: "Oct 28, 2025" },
  { slug: "answer-engines-position-zero", category: "AEO", title: "Optimizing for Answer Engines: Position Zero Explained", excerpt: "How to structure content so answer engines, voice assistants, and featured snippets surface it at Position Zero.", date: "Dec 5, 2025" },
  { slug: "local-search-dubai", category: "Local SEO", title: "Dominating Local Search in Dubai: A Practical Guide", excerpt: "Actionable steps to improve your Google Business Profile and local citations for maximum visibility in Dubai search.", date: "Sep 30, 2025" },
  { slug: "semantic-seo-entities-keywords", category: "Content", title: "Semantic SEO: Writing for Entities, Not Just Keywords", excerpt: "Move beyond keyword stuffing and build topical authority through entity-based, semantic content optimisation.", date: "Jan 14, 2026" },
  { slug: "tracking-seo-metrics-revenue", category: "Analytics", title: "Tracking What Matters: Metrics That Actually Drive Revenue", excerpt: "Stop chasing vanity metrics. Learn how to measure SEO ROI and the metrics that actually drive business revenue.", date: "Feb 22, 2026" },
  { slug: "what-chatgpt-sees-when-it-looks-for-your-dubai-business", category: "GEO", title: "What ChatGPT Sees When Someone Asks It to Find Your Dubai Business", excerpt: "A walk through what AI engines actually see when searching for Dubai businesses, and why most are invisible.", date: "May 15, 2026" },
  { slug: "two-dubai-businesses-one-invisible-online", category: "SEO Strategy", title: "Two Dubai Businesses, Same Quality, One Invisible Online", excerpt: "The gap between Dubai businesses that rank and those that do not is rarely quality. It is almost always visibility.", date: "May 15, 2026" },
  { slug: "the-honest-guide-to-seo-timelines-in-dubai", category: "SEO Strategy", title: "The Honest Guide to SEO Timelines: What Dubai Businesses Should Actually Expect", excerpt: "Honest month-by-month expectations for how long SEO takes in Dubai, from first cleanup to real results.", date: "May 15, 2026" },
];

const seen = new Set(KEEPERS.map((p) => p.slug));
const rest = [...generatedBlogPosts, ...generatedBlogPosts2, ...longFormArticles]
  .filter((p) => {
    if (seen.has(p.slug)) return false;
    seen.add(p.slug);
    return true;
  })
  .map((p) => ({
    slug: p.slug,
    category: p.category,
    title: p.title,
    excerpt: p.excerpt,
    date: p.date,
    image: imageForPage({ slug: p.slug, category: p.category, title: p.title }).src,
  }));

const blogIndex = [...KEEPERS.map((p) => ({
  ...p,
  image: imageForPage({ slug: p.slug, category: p.category, title: p.title }).src,
})), ...rest];
const blogOut = `// AUTO-GENERATED by scripts/gen-keyword-index.ts — do not edit by hand.
// Slim listing metadata only. Full article bodies stay out of the main JS bundle.
export interface BlogIndexEntry {
  slug: string;
  category: string;
  title: string;
  excerpt: string;
  date: string;
  image: string;
}

export const blogIndex: BlogIndexEntry[] = ${JSON.stringify(blogIndex)};
`;
writeFileSync(join(__dirname, "..", "src", "data", "blogIndex.ts"), blogOut, "utf-8");
console.log(`✓ Generated blogIndex.ts with ${blogIndex.length} posts`);
