/**
 * Generates src/data/keywordIndex.ts: a lightweight slug + keyword list for
 * every keyword page. KeywordPage.tsx uses this (a few KB) to build related
 * links instead of importing the full ~1MB keywordPages dataset into its chunk.
 *
 * Runs before `vite build` so the index is always in sync with the page data.
 *   npx tsx scripts/gen-keyword-index.ts
 */

import { writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { keywordPages } from "../src/data/keywordPages";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const index = Object.values(keywordPages).map((p) => ({ slug: p.slug, keyword: p.keyword }));

const out = `// AUTO-GENERATED by scripts/gen-keyword-index.ts — do not edit by hand.
// Lightweight slug + keyword index used by KeywordPage for related-links
// scoring without pulling the full keywordPages dataset into the page chunk.
export interface KeywordIndexEntry {
  slug: string;
  keyword: string;
}

export const keywordIndex: KeywordIndexEntry[] = ${JSON.stringify(index)};
`;

const target = join(__dirname, "..", "src", "data", "keywordIndex.ts");
writeFileSync(target, out, "utf-8");
console.log(`✓ Generated keywordIndex.ts with ${index.length} entries`);
