// Official and primary sources cited on industry pages and guides.
// Guides inherit their industry's sources unless listed in POST_SOURCES.
export interface Source {
  name: string;
  url: string;
}

const S = {
  starter: { name: "SEO Starter Guide, Google Search Central", url: "https://developers.google.com/search/docs/fundamentals/seo-starter-guide" },
  helpful: { name: "Creating helpful, reliable, people-first content, Google Search Central", url: "https://developers.google.com/search/docs/fundamentals/creating-helpful-content" },
  ai: { name: "AI features and your website, Google Search Central", url: "https://developers.google.com/search/docs/appearance/ai-features" },
  sd: { name: "Introduction to structured data, Google Search Central", url: "https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data" },
  multi: { name: "Managing multi-regional and multilingual sites, Google Search Central", url: "https://developers.google.com/search/docs/specialty/international/managing-multi-regional-sites" },
  cwv: { name: "Core Web Vitals, Google Search Central", url: "https://developers.google.com/search/docs/appearance/core-web-vitals" },
  job: { name: "Job posting structured data, Google Search Central", url: "https://developers.google.com/search/docs/appearance/structured-data/job-posting" },
  gbpRank: { name: "Tips to improve your local ranking on Google, Google Business Profile Help", url: "https://support.google.com/business/answer/7091" },
  gbpGuide: { name: "Guidelines for representing your business on Google, Google Business Profile Help", url: "https://support.google.com/business/answer/3038177" },
  conv: { name: "About conversion measurement, Google Ads Help", url: "https://support.google.com/google-ads/answer/1722022" },
  ga4: { name: "Introducing the next generation of Google Analytics, Analytics Help", url: "https://support.google.com/analytics/answer/10089681" },
  fta: { name: "Federal Tax Authority (UAE)", url: "https://tax.gov.ae" },
  mof: { name: "Ministry of Finance (UAE)", url: "https://mof.gov.ae" },
  moec: { name: "Ministry of Economy (UAE)", url: "https://www.moec.gov.ae" },
  mohre: { name: "Ministry of Human Resources and Emiratisation (MOHRE)", url: "https://www.mohre.gov.ae" },
  dld: { name: "Dubai Land Department", url: "https://dubailand.gov.ae" },
  det: { name: "Dubai Department of Economy and Tourism (DET)", url: "https://www.dubaidet.gov.ae" },
  dm: { name: "Dubai Municipality", url: "https://www.dm.gov.ae" },
  rta: { name: "Roads and Transport Authority (RTA), Dubai", url: "https://www.rta.ae" },
  khda: { name: "Knowledge and Human Development Authority (KHDA), Dubai", url: "https://www.khda.gov.ae" },
  adek: { name: "Abu Dhabi Department of Education and Knowledge (ADEK)", url: "https://www.adek.gov.ae" },
  moe: { name: "Ministry of Education (UAE)", url: "https://www.moe.gov.ae" },
  dha: { name: "Dubai Health Authority (DHA)", url: "https://www.dha.gov.ae" },
  doh: { name: "Department of Health, Abu Dhabi", url: "https://www.doh.gov.ae" },
  mohap: { name: "Ministry of Health and Prevention (MOHAP)", url: "https://mohap.gov.ae" },
  moj: { name: "Ministry of Justice (UAE)", url: "https://www.moj.gov.ae" },
  lad: { name: "Legal Affairs Department, Government of Dubai", url: "https://legal.dubai.gov.ae" },
  difc: { name: "Dubai International Financial Centre (DIFC)", url: "https://www.difc.ae" },
  adgm: { name: "Abu Dhabi Global Market (ADGM)", url: "https://www.adgm.com" },
  cbuae: { name: "Central Bank of the UAE (insurance regulator)", url: "https://www.centralbank.ae" },
  uae: { name: "The official portal of the UAE Government (u.ae)", url: "https://u.ae" },
  iata: { name: "International Air Transport Association (IATA)", url: "https://www.iata.org" },
  icp: { name: "Federal Authority for Identity, Citizenship, Customs and Port Security (ICP)", url: "https://icp.gov.ae" },
  dct: { name: "Department of Culture and Tourism, Abu Dhabi", url: "https://dct.gov.ae" },
  dwtc: { name: "Dubai World Trade Centre (DWTC)", url: "https://www.dwtc.com" },
  dewa: { name: "Dubai Electricity and Water Authority (DEWA)", url: "https://www.dewa.gov.ae" },
  dcd: { name: "Dubai Civil Defence", url: "https://www.dcd.gov.ae" },
} satisfies Record<string, Source>;

export const INDUSTRY_SOURCES: Record<string, Source[]> = {
  "real-estate": [S.dld, S.gbpRank, S.helpful],
  construction: [S.dm, S.gbpRank, S.helpful],
  "car-dealers": [S.rta, S.gbpRank, S.gbpGuide],
  "cleaning-companies": [S.det, S.gbpRank, S.gbpGuide],
  "maid-services": [S.mohre, S.gbpRank, S.gbpGuide],
  "painting-carpentry": [S.det, S.gbpRank, S.gbpGuide],
  "home-furniture": [S.det, S.gbpRank, S.sd],
  education: [S.khda, S.adek, S.moe, S.helpful],
  "spas-wellness": [S.dm, S.gbpRank, S.gbpGuide],
  "beauty-salons": [S.dm, S.gbpRank, S.gbpGuide],
  "holistic-healing": [S.dha, S.doh, S.helpful],
  "mental-health-therapists": [S.dha, S.doh, S.helpful],
  "yoga-studios": [S.gbpRank, S.gbpGuide, S.helpful],
  "hospitals-clinics": [S.dha, S.doh, S.mohap, S.helpful],
  "dental-clinics": [S.dha, S.doh, S.gbpRank],
  "cardiology-heart-clinics": [S.dha, S.doh, S.helpful],
  "gyms-fitness": [S.gbpRank, S.gbpGuide, S.conv],
  restaurants: [S.dm, S.gbpRank, S.sd],
  hotels: [S.det, S.gbpRank, S.multi],
  "dermatology-clinics": [S.dha, S.doh, S.helpful],
  "physiotherapy-clinics": [S.dha, S.doh, S.gbpRank],
  "aesthetic-clinics": [S.dha, S.doh, S.mohap, S.helpful],
  "ac-maintenance": [S.det, S.gbpRank, S.gbpGuide],
  "pest-control": [S.dm, S.gbpRank, S.gbpGuide],
  "movers-packers": [S.det, S.gbpRank, S.gbpGuide],
  "business-setup-consultants": [S.det, S.moec, S.uae, S.helpful],
  "accounting-firms": [S.moec, S.fta, S.helpful],
  "vat-corporate-tax-consultants": [S.fta, S.mof, S.helpful],
  "interior-design": [S.dm, S.gbpRank, S.helpful],
  "car-rental": [S.rta, S.gbpRank, S.conv],
  "tuition-centres": [S.khda, S.gbpRank, S.helpful],
  "certification-training": [S.khda, S.helpful, S.sd],
  "desert-safari": [S.det, S.gbpRank, S.multi],
  "yacht-charters": [S.det, S.gbpRank, S.multi],
  "recruitment-agencies": [S.mohre, S.job, S.helpful],
  "property-management": [S.dld, S.gbpRank, S.helpful],
  "holiday-homes": [S.det, S.gbpRank, S.sd],
  "coworking-spaces": [S.det, S.gbpRank, S.gbpGuide],
  "law-firms": [S.moj, S.lad, S.difc, S.adgm],
  "insurance-brokers": [S.cbuae, S.dha, S.doh, S.helpful],
  "travel-agencies": [S.det, S.iata, S.gbpRank, S.helpful],
  "event-management": [S.det, S.dct, S.gbpRank, S.helpful],
  "mep-contractors": [S.dm, S.dewa, S.dcd, S.helpful],
};

export const POST_SOURCES: Record<string, Source[]> = {
  "questions-to-ask-before-hiring-a-marketing-agency-dubai": [S.helpful, S.starter],
  "get-recommended-by-chatgpt-google-ai-overviews": [S.ai, S.sd, S.helpful],
  "track-whatsapp-call-form-leads-uae": [S.conv, S.ga4],
  "google-business-profile-setup-checklist-dubai": [S.gbpRank, S.gbpGuide],
  "how-much-should-a-uae-business-spend-on-marketing": [S.conv, S.helpful],
  "seo-vs-google-ads-dubai-which-first": [S.starter, S.conv],
  "arabic-english-bilingual-website-seo-uae": [S.multi, S.starter],
  "website-traffic-but-no-enquiries-conversion-checklist": [S.cwv, S.ga4, S.conv],
  "seo-vs-aeo-vs-geo-explained": [S.starter, S.ai, S.sd],
  "job-posting-seo-attract-candidates-uae": [S.job, S.mohre],
  "trakheesi-permit-property-advertising-dubai": [S.dld, S.uae],
  "landlord-content-ejari-rental-index-property-managers": [S.dld, S.helpful],
  "dtcm-holiday-home-licence-guide-operators": [S.det, S.uae],
  "pro-services-marketing-dubai": [S.mohre, S.uae, S.gbpRank],
  "abu-dhabi-business-setup-leads": [S.uae, S.adgm, S.gbpGuide],
  "marketing-company-formation-to-foreign-founders": [S.uae, S.moec, S.multi],
  "audit-firm-marketing-dubai": [S.moec, S.fta, S.helpful],
  "bookkeeping-services-marketing-dubai": [S.fta, S.helpful],
  "vat-consultant-marketing-dubai": [S.fta, S.gbpRank, S.helpful],
  "e-invoicing-services-marketing-uae": [S.mof, S.fta, S.ai],
  "tax-consultant-marketing-uae": [S.fta, S.mof, S.helpful],
  "law-firm-practice-area-pages-seo": [S.moj, S.lad, S.sd, S.ai],
  "ethical-marketing-for-therapists-uae": [S.dha, S.doh, S.helpful],
  "holiday-package-pages-seo-uae": [S.sd, S.multi, S.helpful],
  "wedding-planner-marketing-dubai": [S.det, S.gbpRank, S.gbpGuide],
  "exhibition-stand-builder-marketing-dubai": [S.dwtc, S.helpful, S.conv],
  "how-travel-agencies-get-more-bookings-uae": [S.det, S.icp, S.gbpRank, S.helpful],
  "corporate-travel-management-marketing-uae": [S.iata, S.helpful, S.conv],
};

// Date the industry pages were last reviewed for accuracy.
export const INDUSTRY_REVIEWED = "2026-09-27";

export const GENERAL_SOURCES: Source[] = [S.helpful, S.starter];
